from .compat import builtin_str as builtin_str, is_py2 as is_py2, str as str
from typing import Any

def to_native_string(string: Any, encoding: str = ...): ...
def unicode_is_ascii(u_string: Any): ...
